title: RedTeamer Blog
tagline: Writeups CTF & AI RedTeaming Labs
description: Explore technical writeups and deep dives into AI RedTeaming and Cyber Security.

theme: jekyll-theme-chirpy

author:
  name: T3chW1zard
  twitter: gkpl0010
  github: Patrickleondev

url: "https://patrickleondev.github.io"
baseurl: "/portfolio/blog"

# Social Links
social:
  name: T3chW1zard
  links:
    - https://github.com/Patrickleondev
    - https://twitter.com/gkpl0010
    - https://www.linkedin.com/in/patrick-léon-gandonou

# Jekyll plugins
plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-archives
  - jekyll-include-cache

# Pagination settings
paginate: 10
paginate_path: /page:num/

# Markdown Settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Chirpy settings
lang: fr-FR
timezone: UTC
avatar: ''
theme_mode: dark

sass:
  style: compressed

# Build settings
exclude:
  - Gemfile
  - vendor
  - .github
  - Dockerfile
  - README.md
  - LICENSE
  - "*.sh"
  - node_modules

# Archive settings (for tags and categories)
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
